# Streamlit配置文件 - 生产环境
[server]
port = 8501
address = "0.0.0.0"
baseUrlPath = ""
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

[browser]
gatherUsageStats = false
showErrorDetails = false

[theme]
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1f2937"

[runner]
magicEnabled = false
installTracer = false
fixMatplotlib = true

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[client]
caching = true
displayEnabled = true
showErrorDetails = false

[global]
developmentMode = false
logLevel = "info"
suppressDeprecationWarnings = true
